### ISSUE TITLE
Error when built-in unzip functionality is not enabled in Windows

### ISSUE THREAD

**Issue by jferris-** [VolantisDev/Launchpad#2]
First time trying to use this. Same issue running as admin.

Launchpad 4.3.0
Windows 10 Pro 64bit - English International

![](https://i.imgur.com/5d3rbW5.png)

**Comment by bmcclure** [comment]
Thanks for the report! You're the first user I've actually heard from who's tried to use Launchpad, so it's really helpful.

I'm working on better error handling for a future release, however, most errors of this type I've seen have occurred because of issues related to the script getting a valid response from network requests. This is supported by the fact that AutoHotKey is the first dependency that gets downloaded, (and I doubt that the AutoHotKey download link stopped working although I will double-check that to make sure).

Can you confirm the version of Launchpad you have installed? Based on the theme I know it's recent. And also, can you send me some details about your setup? Are you on Windows 10, and is it 64-bit or 32-bit? I can't seem to reproduce this error so I'm trying to determine what may be different between our setup that I can account for in the script.

**Comment by bmcclure** [comment]
Also, if possible, could you check two other locations for me?

`%APPDATA%\Volantis\Launchpad` - Does the directory exist and is there a "State.json" file in it?
`%TEMP%\Launchpad` - Does it exist and is there anything in it?

Thanks!

**Comment by jferris-** [comment]
> 
> 
> Also, if possible, could you check two other locations for me?
> 
> `%APPDATA%\Volantis\Launchpad` - Does the directory exist and is there a "State.json" file in it?
> `%TEMP%\Launchpad` - Does it exist and is there anything in it?
> 
> In particular, if it started downloading AutoHotKey then seeing if it left any remnants in the temp directory might help to pinpoint exactly where the issue occurred.
> 
> I added debug logging the other day but haven't started actually logging any data yet. I can add some additional logging during the dependency initialization process to help pinpoint this issue if needed.
> 
> Thanks!

Sorry, I completely forgot to fill in any helpful details. I've updated my first comment with Windows OS details.

As for '%APPDATA%\Volantis\Launchpad', yes the json file exists. Its contents: 
`{"State":{"InstalledComponents":{"Themes":1},"Versions":{"Dependencies":"20210110235201","Themes":"20210110235201"}}}`

%TEMP%\Launchpad also exists;
![](https://i.imgur.com/PMzgB6L.gif)

**Comment by bmcclure** [comment]
I think you've just figured it out! Currently, Launchpad uses the built-in shell unzipping functionality to extract downloaded archives. Since you're one of the first users other than me, I wonder how many others will have removed the shell unzip functionality and run into similar issues.

Technically, you could unzip the file to your main app dir under Launchpad\Vendor\AutoHotKey, and then adjust the state file to indicate it's already installed, however you'd have to repeat that for each dependency so it would be a hassle.

I've been on a mission to lower the number of external dependencies and handle as much as possible internally, however this might be a case where it makes sense for me to download an extraction tool (perhaps the 7zip CLI) as the first dependency and use that for extracting zip files.

I'll work today on finding a solution for your use case and can hopefully have a new release out this evening that can function without the shell's unzip functionality. Or if nothing else, I'll at least have a better workaround I can give you.

**Comment by bmcclure** [comment]
I've included 7za.exe with the latest commit of Launchpad and am using that for extraction. It is working in my tests so far, however, through testing I uncovered an issue related to dependencies always being detected as out-of-date.

I'm just fixing the version handling and refactoring how dependencies are installed now, then I expect to be ready to make a full release of Launchpad tonight that should 🤞 work for you and speed up launching quite a bit.

**Comment by bmcclure** [comment]
@jferris- I have a version released now which should hopefully work properly for you: https://github.com/VolantisDev/Launchpad/releases/tag/4.4.0

Let me know if you run into further bugs, or if you have any questions once you get started. Better documentation is coming, so I apologize for the lack of documentation currently.
